### ISSUE TITLE
Code "Comparison analysis of Q-Learning and Sarsa algorithms";

### ISSUE THREAD

**Issue by Pyjamask** [sichkar-valentyn/Reinforcement_Learning_in_Python#22]
Hello,
I want to thank you for the work done, it is a remarkable job
But I'd like to ask you a few questions about program execution
I can't find in the source code the part that deals with the comparison between the two Comparison analysis of Q-Learning and Sarsa algorithms?
Best regards

**Comment by sichkar-valentyn** [comment]
Hi there!
Thanks for your feedback.

That part of the code is currently my research work I am working with.
I might publish it later.
